# ---------- Flyway ----------
FROM flyway/flyway:latest AS flyway


# ---------- Build ----------
FROM node:22-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY prisma ./prisma
COPY src ./src
COPY db ./db
COPY tsconfig*.json ./
COPY nest-cli.json ./

RUN npx prisma generate
RUN npm run build


# ---------- Production ----------
FROM node:22-alpine AS production

WORKDIR /app

ENV NODE_ENV=production

COPY package*.json ./

RUN npm install

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules/@prisma ./node_modules/@prisma
COPY --from=builder /app/db ./db

# Flyway binary + drivers
COPY --from=flyway /flyway /flyway

EXPOSE 3000

CMD ["node", "dist/main.js"]